/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog2.vista;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import prog2.adaptador.Adaptador;

public class AppMercatUb extends javax.swing.JFrame {

    private Adaptador control;

    public AppMercatUb() {
        initComponents();
        control = new Adaptador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        etTitol = new javax.swing.JLabel();
        btnGestioClients = new javax.swing.JButton();
        btnGestioArticles = new javax.swing.JButton();
        btnGestioComandes = new javax.swing.JButton();
        btnGravarFitxer = new javax.swing.JButton();
        btnRecuperarDades = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etTitol.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etTitol.setText("Menú Principal");

        btnGestioClients.setText("Gestió de Clients");
        btnGestioClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioClientsActionPerformed(evt);
            }
        });

        btnGestioArticles.setText("Gestió d'Articles");
        btnGestioArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioArticlesActionPerformed(evt);
            }
        });

        btnGestioComandes.setText("Gestió de Comandes");
        btnGestioComandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioComandesActionPerformed(evt);
            }
        });

        btnGravarFitxer.setText("Gravar Dades");
        btnGravarFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarFitxerActionPerformed(evt);
            }
        });

        btnRecuperarDades.setText("Recuperar Dades");
        btnRecuperarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarDadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(etTitol, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGestioClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGestioArticles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGestioComandes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGravarFitxer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRecuperarDades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(etTitol)
                .addGap(30, 30, 30)
                .addComponent(btnGestioClients)
                .addGap(18, 18, 18)
                .addComponent(btnGestioArticles)
                .addGap(18, 18, 18)
                .addComponent(btnGestioComandes)
                .addGap(18, 18, 18)
                .addComponent(btnGravarFitxer)
                .addGap(18, 18, 18)
                .addComponent(btnRecuperarDades)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestioClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioClientsActionPerformed
        FrmGestioClients formGestioClients = new FrmGestioClients(control);
        formGestioClients.pack();
        formGestioClients.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_btnGestioClientsActionPerformed

    private void btnGestioArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioArticlesActionPerformed
        FrmGestioArticles formGestioArticles = new FrmGestioArticles(control);
        formGestioArticles.pack();
        formGestioArticles.setVisible(true);

    }//GEN-LAST:event_btnGestioArticlesActionPerformed

    private void btnGestioComandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioComandesActionPerformed
        FrmGestioComandes formGestioComandes = new FrmGestioComandes(control);
        formGestioComandes.pack();
        formGestioComandes.setVisible(true);
    }//GEN-LAST:event_btnGestioComandesActionPerformed

    private void btnGravarFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarFitxerActionPerformed
        try {
            String nomFitxer = JOptionPane.showInputDialog(this, "Introdueix el nom de l'arxiu:", "Guardar Dades", JOptionPane.QUESTION_MESSAGE);
            this.control.guardaDades(nomFitxer);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarFitxerActionPerformed

    private void btnRecuperarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarDadesActionPerformed
        try {
            File fitxer;
            JFileChooser seleccio = new JFileChooser();
            int resultat = seleccio.showOpenDialog(this);
            if (resultat == JFileChooser.APPROVE_OPTION) {
                fitxer = seleccio.getSelectedFile();
                this.control.carregaDades(fitxer.toString());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRecuperarDadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMercatUb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMercatUb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMercatUb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMercatUb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMercatUb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestioArticles;
    private javax.swing.JButton btnGestioClients;
    private javax.swing.JButton btnGestioComandes;
    private javax.swing.JButton btnGravarFitxer;
    private javax.swing.JButton btnRecuperarDades;
    private javax.swing.JLabel etTitol;
    private javax.swing.JFrame jFrame1;
    // End of variables declaration//GEN-END:variables
}
